version: "3.9"
services:
  demo_nginx:
    container_name: demo_nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - demo-network

  php-fpm:
    container_name: "demo_php-fpm"
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: serverName=php-fpm
      APP_ENV: dev
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mariadb
    networks:
      - demo-network

  mariadb:
    container_name: demo_mariadb
    image: mariadb:latest
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - demo-network

networks: 
  demo-network:
    driver: bridge  